# Generated by Django 4.1.7 on 2023-04-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('food_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=20)),
                ('catagory', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('avg_review', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tb_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Qr_no', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_food_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_price', models.IntegerField(blank=True, null=True)),
                ('modification', models.CharField(blank=True, max_length=100, null=True)),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.food_item')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tb_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.table'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('exit_status', models.BooleanField(blank=True, null=True)),
                ('bill_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.order')),
            ],
        ),
    ]
